# Generated by Django 4.1 on 2023-09-12 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_book_options_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
