# Generated by Django 4.1 on 2023-09-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="test",
            field=models.DateField(blank=True, null=True),
        ),
    ]
